version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./html:/usr/share/nginx/html"
    depends_on:
      - php
    networks:
      - network_app

  php:
    image: nanoninja/php-fpm:latest
    volumes:
      - "./html:/usr/share/nginx/html"
    restart: always
    depends_on:
      - mysql
    networks:
      - network_app

  mysql:
    image: mysql:latest
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD= ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - network_app

networks:
  network_app:
    driver: bridge
    ipam:
     config:
       - subnet: 172.16.98.0/24

volumes:
  mysql_data: