version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./html:/usr/share/nginx/html"
    depends_on:
      - php

  php:
    image: nanoninja/php-fpm:latest
    volumes:
      - "./html:/usr/share/nginx/html"
    restart: always
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD= ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: